- name: creating required directories
  file:
    state: directory
    mode: 0755
    path: "{{ item }}"
  with_items:
    - /tmp/containerd
    - /etc/containerd

- name: downloading containerd binaries (arm64)
  unarchive:
    src: "{{ containerd.containerd_arm64_url }}"
    remote_src: true
    dest: /tmp/containerd
    mode: 0755
  when: ansible_architecture in [ "aarch64", "arm64" ]

- name: downloading containerd binaries (amd64)
  unarchive:
    src: "{{ containerd.containerd_amd64_url }}"
    remote_src: true
    dest: /tmp/containerd
    mode: 0755
  when: ansible_architecture == "amd64"

- name: moving containerd binaries to /usr/local/bin
  copy:
    remote_src: true
    src: "/tmp/containerd/bin/{{ item }}"
    dest: /usr/local/bin
    mode: 0751
  with_items:
    - containerd
    - containerd-shim
    - containerd-shim-runc-v1
    - containerd-shim-runc-v2
    - containerd-stress
    - ctr

- name: downloading runc (arm64)
  get_url:
    url: "{{ containerd.runc_arm64_url }}"
    dest: /usr/local/bin/runc
    mode: 0751
  when: ansible_architecture in [ "aarch64", "arm64" ]

- name: downloading runc (amd64)
  get_url:
    url: "{{ containerd.runc_amd64_url }}"
    dest: /usr/local/bin/runc
    mode: 0751
  when: ansible_architecture == "amd64"

- name: copy containerd config
  copy:
    src: config.toml
    dest: /etc/containerd/config.toml
    mode: 0644

- name: download containerd.service file
  get_url:
    url: "{{ containerd.containerd_service_url }}"
    dest: /etc/systemd/system/containerd.service
    mode: 0644

- name: start & enable containerd service
  systemd:
    name: containerd
    state: started
    enabled: true
