- name: downloading gpg key
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes.gpg
    owner: root
    group: root
    mode: 0644

- name: adding kubernetes repository to apt
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kubernetes.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes

- name: installing kubeadm, kubectl & kubelet
  apt:
    name:
      - "kubeadm={{ kubernetes.version }}"
      - "kubectl={{ kubernetes.version }}"
      - "kubelet={{ kubernetes.version }}"

- name: pinning kubeadm, kubectl & kubelet
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubeadm
    - kubectl
    - kubelet

- name: start & enable kubelet service
  systemd:
    name: kubelet
    state: started
    enabled: true
