apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: default
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - sleep infinity
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        volumeMounts:
        - name: config
          mountPath: /etc/secrets
      volumes:
        - name: config
          secret:
            secretName: mysecret
            items:
              - key: secret.json
                path: mysecret.json
      restartPolicy: Always
---
