apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune
  namespace: default
  labels:
    app: fortune
spec:
  selector:
    matchLabels:
      app: fortune
  replicas: 1
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
      - name: fortuneloop
        image: fortuneloop:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: html
          mountPath: /var/htdocs
      - name: webserver
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
        - name: html
          emptyDir: {}
          # emptyDir:
          #   medium: Memory
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: fortune
  namespace: default
spec:
  selector:
    app: fortune
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
    nodePort: 30001
---
