# *not* idempotent
# Ensure that this playbook is ran only once

- hosts: all
  become: true
  tasks:
    - name: enable linux cgroups
      replace:
        path: /boot/cmdline.txt
        regexp: '$'
        replace: ' cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
