apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongoexpress-deployment
  namespace: default
  labels:
    app: mongoexpress-deployment
spec:
  selector:
    matchLabels:
      app: mongoexpress
  replicas: 1
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
      - name: mongoexpress
        image: mongo-express:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-root-user

        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-root-password

        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongoexpress-secret
              key: mongoexpress-user

        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongoexpress-secret
              key: mongoexpress-password

        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: mongodb-url
        ports:
        - containerPort: 8081
          name: mongoexpress
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
  namespace: default
spec:
  selector:
    app: mongoexpress
  type: LoadBalancer
  ports:
  - name: mongoexpress-service
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30001
---
