apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
  namespace: default
spec:
  schedule: "*/1 * * * *"
  # at the least, the pod must start running at 15s past the scheduled time,
  # otherwise fail the job
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: busybox
            args:
              - /bin/sh
              - -c
              - date
          restartPolicy: OnFailure
---
