apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-reg
  namespace: default
  labels:
    app: private-reg
spec:
  selector:
    matchLabels:
      app: private-reg
  replicas: 1
  template:
    metadata:
      labels:
        app: private-reg
    spec:
      imagePullSecrets:
      - name: dockerhubcreds
      containers:
      - name: liveness
        image: murtazau/liveness:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /probe
            port: 8080
          initialDelaySeconds: 2 # default 0s (inital delay before probing starts)
          timeoutSeconds: 5      # default 1s (if the response time exceeds 5, kill)
          periodSeconds: 1       # default 10s (time period between each probe)
          failureThreshold: 3    # default 3 (no. of failures before killing)
          successThreshold: 1    # default 1
        ports:
        - containerPort: 8080
          name: http
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: private-reg
  namespace: default
spec:
  selector:
    app: private-reg
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
    nodePort: 30001
---
