apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname
  namespace: default
  labels:
    app: hostname
spec:
  selector:
    matchLabels:
      app: hostname
  replicas: 3
  template:
    metadata:
      labels:
        app: hostname
    spec:
      containers:
      - name: hostname
        image: murtazau/hostname:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: hostname
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: hostname
  namespace: default
spec:
  selector:
    app: hostname
  type: NodePort
  ports:
  - name: hostname
    protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30000
---
