apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce     # RWO
    - ReadOnlyMany      # ROX
  persistentVolumeReclaimPolicy: Delete
  storageClassName: managed-nfs
  nfs:
    server: 192.168.0.102
    path: /srv/nfs
