apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ssd-monitor
  namespace: default
  labels:
    app: ssd-monitor
spec:
  selector:
    matchLabels:
      app: ssd-monitor
  template:
    metadata:
      labels:
        app: ssd-monitor
    spec:
      nodeSelector:
        disk: ssd
      containers:
      - name: ssd-monitor
        image: ssd-monitor:latest
        imagePullPolicy: IfNotPresent
---
