apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless
  namespace: default
  labels:
    app: headless
spec:
  selector:
    matchLabels:
      app: headless
  replicas: 1
  template:
    metadata:
      labels:
        app: headless
    spec:
      containers:
      - name: headless
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: headless
  namespace: default
spec:
  clusterIP: None
  selector:
    app: headless
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
---
