apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  storageClassName: nfs-rpi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
---
