apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
  namespace: default
  labels:
    app: kubia
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: kubia
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
          periodSeconds: 1
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: kubia
  namespace: default
spec:
  selector:
    app: kubia
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
    nodePort: 30001
---
